services:
  pedido-db:
    image: mongo:6
    container_name: pedido_db
    ports:
      - '27017:27017'
    volumes:
      - pedido_db_data:/data/db

  pedido-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pedido_service
    environment:
      MONGO_URI: mongodb://pedido-db:27017/pedidos_db
    ports:
      - '3001:3000'
    depends_on:
      - pedido-db

volumes:
  pedido_db_data:
