apiVersion: v1
kind: ConfigMap
metadata:
  name: pedido-config
  labels:
    app: pedido-app
data:
  PORT: '3000'
  CUSTOMER_API_URI: 'http://a2d71c620ce534f20ad6b9c24a3f2cde-1281406927.us-east-1.elb.amazonaws.com:8080/api/v1/cliente'
  PRODUCT_API_URI: 'http://ab6949e5e906d46cf815bc816e2814f6-446211351.us-east-1.elb.amazonaws.com:8080/api/v1/produtos'
