apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedido-deployment
  labels:
    app: pedido-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedido-app
  template:
    metadata:
      labels:
        app: pedido-app
    spec:
      serviceAccountName: pedido-service-account # AWS IAM
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: pedido-app
          image: 666881761373.dkr.ecr.us-east-1.amazonaws.com/order:latest
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: pedido-config
                  key: PORT
            - name: MONGO_URI_ONLINE
              valueFrom:
                secretKeyRef:
                  name: pedido-secrets
                  key: MONGO_URI_ONLINE
            - name: CUSTOMER_API_URI
              valueFrom:
                configMapKeyRef:
                  name: pedido-config
                  key: CUSTOMER_API_URI
            - name: PRODUCT_API_URI
              valueFrom:
                configMapKeyRef:
                  name: pedido-config
                  key: PRODUCT_API_URI
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
