apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedido-service
  labels:
    app: pedido-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedido-service
  template:
    metadata:
      labels:
        app: pedido-service
    spec:
      serviceAccountName: pedido-service-account # gostei dessa ideia para integrar com o AWS IAM
      containers:
        - name: pedido-container
          image: 666881761373.dkr.ecr.us-east-1.amazonaws.com/order:latest
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
              name: pedido-config
            - secretRef:
              name: pedido-secrets
          resources:
            limits:
              cpu: '0.5'
              memory: '512Mi'
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
