apiVersion: v1
kind: Service
metadata:
  name: pedido-service
  labels:
    app: pedido-service
spec:
  type: LoadBalancer
  selector:
    app: pedido-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
