name: CI/CD - Build and Deploy to EKS

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed  # Only triggers when a PR is merged
    branches:
      - main

jobs:
  build_and_push:
    name: Build, Push to ECR, and Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Iniciando com credenciais adicionadas anteriormente
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Login no Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Buildando a imagem docker
      - name: Build Docker Image
        run: |
          docker build -t order:latest .

      # Enviar a imagem para o ECR
      - name: Push Docker Image to Amazon ECR
        env:
          ECR_URL: 666881761373.dkr.ecr.us-east-1.amazonaws.com/order #Alterar se necessário
        run: |
          docker tag order:latest $ECR_URL:latest
          docker push $ECR_URL:latest

      - name: Configure Kubectl
        env:
          EKS_CLUSTER_NAME: EKS-fiap-tech-challenge
        run: |
          aws eks update-kubeconfig --region us-east-1 --name $EKS_CLUSTER_NAME

      - name: Apply Kubernetes
        run: |
          kubectl apply -f k8s/configMap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/serviceAccount.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/deployment.yaml
          
        # kubectl rollout restart deployment pedido-service
